### PR TITLE
go.mod: restore Go 1.22 support

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Go 1.22 has not reached its EOL yet

### CODE REVIEW

**Review by deitch — DISMISSED** [review]
Thanks @AkihiroSuda

**Comment by deitch** [comment]
There's some crypto changes that need to be changed for this to pass. See the failing tests.

**Comment by AkihiroSuda** [comment]
https://github.com/diskfs/go-diskfs/actions/runs/11157473532/job/31122367815?pr=262
```
Error: vet: filesystem/fat32/fat32_test.go:267:20: chacha.Read undefined (type *rand.ChaCha8 has no field or method Read)
```
- https://github.com/diskfs/go-diskfs/pull/260/files#r1789566027

**Comment by deitch** [comment]
Yeah. See my comment on the other issue. Just switch it back to crypto/rand in this PR and it should be clean.

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
All looks good. You ready for merge @AkihiroSuda ?

**Comment by AkihiroSuda** [comment]
> All looks good. You ready for merge @AkihiroSuda ?

Yes, thanks

**Comment by deitch** [comment]
Thanks for driving this @AkihiroSuda

**Pull request merged**
