### PR TITLE
squashfs: add zstd support

### PR DESCRIPTION
**Pull request by ncw**

### CODE REVIEW

**Review by deitch — APPROVED** [review]
This is great. Thank you!

**Comment by deitch** [comment]
The lint failure seems to be a 1.21.5 thing. I wonder what changed from 1.21.4.
In any case, golangci-lint 1.55 fixes that issue, but opens a bunch more. I will fix those and merge it in, then you can rebase on that.

**Comment by deitch** [comment]
OK, try now. Rebase all of your PRs and push, and let's see if it passes.

**Comment by ncw** [comment]
Rebased!

**Pull request merged**
