### PR TITLE
Allow resizing a GPT

### PR DESCRIPTION
**Pull request by paul-rodriguez**
These changes allow:
* observing the total size and last data sector of a GPT
* resizing a GPT (for example to make it fit its block device)
* expanding a GPT partition

### CODE REVIEW

**Comment by paul-rodriguez** [comment]
> The assumption is that one would expand the partition, and then call `table.Write()` to write it to disk?

Yes indeed.

> Can we add some tests? Look at how `table_test.go` does it, which probably is the right place for it. I wouldn't want to affect the original `testdata/gpt.img`, but maybe it can be copied to a tmpdir, then modified, and read using the library to see that the changes took? Since we already test the reading of partition tables independently, we can rely on those to validate the changes.

Sure thing, thanks for the pointers.

**Comment by paul-rodriguez** [comment]
@deitch I have pushed some unit tests for the Resize and Expand functions. My apologies if this mention is not good etiquette!

**Review by deitch — DISMISSED** [review]

**Comment by deitch** [comment]
Not a problem at all. Thank you for this. Let's let CI run.

**Comment by deitch** [comment]
Some linting issues.

**Comment by paul-rodriguez** [comment]
It should be ok now

**Comment by deitch** [comment]
Looks good. Are you ready to go with this?

**Review by deitch — APPROVED** [review]

**Comment by paul-rodriguez** [comment]
Yes, it works fine for my purposes. Thank you!

**Comment by deitch** [comment]
Thanks @paul-rodriguez

**Pull request merged**
