### PR TITLE
Migrate project to go modules

### PR DESCRIPTION
**Pull request by alkersan**

### CODE REVIEW

**Comment by alkersan** [comment]
Hm, not sure what is the problem, but tests fail
```
--- FAIL: TestElToritoValidationEntry (0.00s)
    eltorito_internal_test.go:64: Mismatched bytes, actual then expected
        01 ef 00 00 68 74 74 70 73 3a 2f 2f 67 69 74 68 75 62 2e 63 6f 6d 2f 64 69 73 6b 66 3c d5 55 aa
        01 ef 00 00 68 74 74 70 73 3a 2f 2f 67 69 74 68 75 62 2e 63 6f 6d 2f 64 69 73 6b 66 37 e2 55 aa
```
Seems the checksum is not what expected

**Comment by deitch** [comment]
I’ll look next week at some point.

**Comment by deitch** [comment]
You are right, it _does_ fail on current master. Strange, that is. Dig in time...

**Comment by deitch** [comment]
No, somehow I have the checksum off. I just recalculated it manually. Opening a PR to fix that, then you can rebase.

**Comment by deitch** [comment]
Rebase and try now.

**Comment by alkersan** [comment]
:+1:

**Comment by deitch** [comment]
Closed via #22

**Pull request closed without merging**
