### PR TITLE
fix reading of partial clusters in fat32

### LINKED ISSUE #108: fat32.File does not not implement io.Writer correctly.
It seems that multiple calls to `fat32.File.Write()` will simply cause previous writes to be overwritten. This is pretty noticeable if one tries to call io.Copy a large reader (32KB+) into it:

```
var src os.File = io.Open(...)
dest, _ = destfs.OpenFile(path, os.O_CREATE|os.O_RDWR)
written, err := io.Copy(dest, src) 
``` 

In this scenario io.Copy will report all src bytes as written and no error is reported. The final file will contain only the last 32KB of the original file (that's because 32KB is the default buffer size used by io.Copy).

### PR DESCRIPTION
**Pull request by deitch**
Fixes #108

### CODE REVIEW

**Comment by deitch** [comment]
@RafaelMarinheiro can you try the branch here and see if it resolves your issue #108? The tests pass now.

**Comment by RafaelMarinheiro** [comment]
Thanks! This fixes the issue with io.Copy, making it work as expected!

Having said that, the code with io.Copy is MUCH slower than the code with ReadAll and a single write. I guess this is happening because now you need to deal with FAT32 bookkeeping on every single Write call. You could have avoided this by postponing some of that bookkeeping to a Close() method in the file, but unfortunately the current API does not have anything like that in it.

Thanks again for the fix!

**Comment by RafaelMarinheiro** [comment]
This seems to have fixed https://github.com/diskfs/go-diskfs/issues/109 as well (at least now I can write a large number of things to the same directory and they show up afterwards). Could it be related in some way?

**Comment by deitch** [comment]
Possibly. The `Read` was broken, which might have done it. Let's merge this in, then follow through on #109

**Pull request merged**
