### PR TITLE
gpt.Read: wrap error (%w) so callers can use errors.Is(err, io.EOF)

### PR DESCRIPTION
**Pull request by stapelberg**

### CODE REVIEW

**Comment by vtolstov** [comment]
why you add wrapping here
```
return nil, fmt.Errorf("Read only %d bytes of GPT from file instead of expected %w", read, len(b))
```
?

**Comment by stapelberg** [comment]
Oops, misread that line. Thanks, fixed now.

**Comment by deitch** [comment]
Thanks. I think a lot of it needs to be updated to take advantage of error wrapping.

**Review by deitch — DISMISSED** [review]

**Comment by stapelberg** [comment]
GitHub Actions CI fails because its Go version is too old: go version go1.12.10 linux/amd64

**Comment by deitch** [comment]
CI is failing because it [tests with go 1.12.6](https://github.com/diskfs/go-diskfs/blob/master/.github/workflows/ci.yaml#L26), which is pretty old and predates error wrapping.

Just update that to something 1.13.x in this PR and update, and it should be ok.

**Comment by stapelberg** [comment]
> CI is failing because it [tests with go 1.12.6](https://github.com/diskfs/go-diskfs/blob/master/.github/workflows/ci.yaml#L26), which is pretty old and predates error wrapping.
> 
> Just update that to something 1.13.x in this PR and update, and it should be ok.

Done

**Comment by deitch** [comment]
I will get it in a separate change.

**Comment by deitch** [comment]
Rebase and try again please

**Comment by stapelberg** [comment]
Rebased. Can you approve the CI run?

**Comment by deitch** [comment]
Who would have thunk that this little change would surface all of these issues? 😬 

Had to come up eventually.

**Comment by stapelberg** [comment]
Still a bunch of lint errors:
```
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /home/runner/go/bin v1.41.0
golangci/golangci-lint info checking GitHub for tag 'v1.41.0'
golangci/golangci-lint info found version: 1.41.0 for v1.41.0/linux/amd64
golangci/golangci-lint info installed /home/runner/go/bin/golangci-lint
level=warning msg="[runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."
diskfs_test.go:69:13: undeclared name: `diskfs` (typecheck)
		d, err := diskfs.Open(tt.path)
		          ^
diskfs_test.go:84:13: undeclared name: `diskfs` (typecheck)
		d, err := diskfs.OpenWithMode(tt.path, diskfs.ReadOnly)
		          ^
diskfs_test.go:103:10: undeclared name: `diskfs` (typecheck)
		format diskfs.Format
		       ^
diskfs_test.go:10:2: "github.com/diskfs/go-diskfs" imported but not used (typecheck)
	"github.com/diskfs/go-diskfs"
	^
```

Do you want to address them separately, too?

**Comment by deitch** [comment]
Yeah, although I have no idea what it is complaining about.

**Comment by deitch** [comment]
Rebase and give it another shot?

**Comment by stapelberg** [comment]
Rebased. Please approve for the CI run :)

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
👍

**Pull request merged**
