### PR TITLE
ext4 read-only for now

### PR DESCRIPTION
**Pull request by deitch**
This is a first attempt at getting ext4 live. To get past some challenging parts, I am focusing on ext4 read-only first. 

The current package `filesystem/ext4/` _does_ pass vet, and can compile. linting will require a lot more cleanup.

There are almost no tests on it, and it has not been tested manually. 

Steps:

1. Clean up the significant number of linting errors
2. Get it to pass minimal current tests
3. Write lots more unit tests, get them to pass
4. Extend the integration tests, get them to pass
5. Do manual testing
6. Convert from draft to regular PR

### CODE REVIEW

**Comment by shanduur** [comment]
Great job! Is there any contribution that I might do to speed things up? E.g. adding tests, docs?

**Comment by deitch** [comment]
Yeah, thank you @shanduur . Tests are next. I would start with unit tests on small functions, as I am positive there are errors of calculation in various places.

FWIW, I _do_ have the beginnings of write capability in a separate local branch, but we should get read working correctly first.

**Comment by deitch** [comment]
If it is just small things, comment on the PR. If it is wholesale additions or changes, just open a PR to the `ext4` branch.

**Comment by deitch** [comment]
lint is clean, that is something. Now it needs tests, both unit and actual integration, to get it to actually work.

**Comment by deitch** [comment]
As far as I am concerned, ext4 read-only is ready. I am going to merge in as soon as CI is clean. ext4-write is for another day, although I have part of it, and may push out a branch.

**Pull request merged**
