### PR TITLE
Adding hyphen to the regex because it is a valid character in file names

### PR DESCRIPTION
**Pull request by phillipsj**
This adds the hyphen to the regex and adds unit tests.

Signed-off-by: Jamie Phillips <jamie.phillips@suse.com>

### CODE REVIEW

**Comment by phillipsj** [comment]
@deitch

**Comment by deitch** [comment]
@phillipsj thanks for bringing this in. I am not sure it is correct. The ecma-119 spec says the following:

```
7.4 Character sets and coding 7.4.1 d-characters and a-characters

Except as specified in 7.4.4, the characters in the descriptors shall be coded according to ECMA-6 (see Appendix A).
The 37 characters in the following positions of the International Reference Version are referred to as d-characters:
3/0 to 3/9
4/1 to 5/10
5/15

7.5 File Identifier
7.5.1 File Identifier format
A File Identifier shall consist of the following sequence:
- File Name: A sequence of zero or more d-characters or d1-characters;
- SEPARATOR 1;
- File Name Extension: A sequence of zero or more d-characters or d1-characters;
- SEPARATOR 2;
- File Version Number: Digits representing a number from 1 to 32 767.
```

So the file name and extension can be just d-characters (ecma-119) or d1-characters (iso-9660), which basically are the same. The d-character list is as above.

The ecma-6 list is [here](https://www.ecma-international.org/wp-content/uploads/ECMA-6_6th_edition_december_1991.pdf).

* 3/0 to 3/9 - characters 0-9
* 4/1 to 5/10 - capital A to capital Z
* 5/15 - `_`

I don't see `-` in there anywhere.

**Comment by phillipsj** [comment]
Hmm, interesting that so many things use that.

**Comment by phillipsj** [comment]
@deitch it seems that is a Joliet thing, we are working with Windows. Would you be open to adding Joliet extension support? https://docs.microsoft.com/en-us/windows/win32/imapi/disc-formats#joliet

**Comment by deitch** [comment]
Sure, it has been a "todo" item for a while, see [here](https://github.com/diskfs/go-diskfs/blob/274de576a1a50620d33bc7ce84064e891780dab2/README.md#tests).

It always is a question of time to do it.

**Pull request closed without merging**
