### PR TITLE
Add VS Code tooling

### PR DESCRIPTION
**Pull request by aol-nnov**
@deitch tooling is factored out into this PR.

Comments are welcome!

### CODE REVIEW

**Comment by aol-nnov** [comment]
> where did you get the devcontainer configs from

VS Code did that for me. Just pressed cmd+shift+p and typed few words in! )

image

> should the .vscode/ be committed

Few files from that directory indeed should be ignored, but according to canonical gitignore, settings and extensions are allowed. https://www.toptal.com/developers/gitignore/api/visualstudiocode

Also, I'd like to share the corresponding plugin: https://marketplace.visualstudio.com/items?itemName=piotrpalarz.vscode-gitignore-generator which is extremely handy!

**Comment by aol-nnov** [comment]
By the way, should we update the root `.gitignore` with the help of plugin I'm referring to?

**Comment by aol-nnov** [comment]
Look, I've added the generated file. What do you think?

**Comment by deitch** [comment]
> Few files from that directory indeed should be ignored, but according to canonical gitignore, settings and extensions are allowed. https://www.toptal.com/developers/gitignore/api/visualstudiocode

I do not know what toptal is, looks like a recruiting site? Although gitignore.io (which is not necessarily authoritative either) recommends the same pattern. 🤷‍♂️ 

It feels strange to me, trying to tell people what extensions they should install and what settings to use. The recommendations do make sense, though, as it is just recommendations. But should we be including vscode specific stuff in the repo?

In any case, I am not sure about all of those recommendations. For example, I only use the 3rd and 4th. If someone wants the extra, that is fine. Not sure we should be pushing them.

Some of the settings as well, although those, I think, we can live with.

**Comment by aol-nnov** [comment]
> I do not know what toptal is, looks like a recruiting site?

Toptal acquired gitignore.io few years ago. All ignore patterns are [available on github](https://github.com/toptal/gitignore.io)
 and are managed by programming community. I've used gitirnore.io for more than a decade now, different languages, different IDEs. It served me well through years.

>  what extensions they should install and what settings to use

As for plugins, this is in no way an enforcement, it is a recommendation. When you open the workspace, a popup is showed informing the user about plugins recommended for comfortable development of the current project.

As for settings.json, it is also for consistency. For example, format on save, newline at the end of file - all that essentials.

Anyway, I'm open to any suggestions regarding any of the configs and, on the other side, invite you to try new vscode plugins if you haven't heard of them before. Chances are high, you'll like them!

**Comment by deitch** [comment]
Nah, I think it is ok. We always can change it if it gets too rough.

**Review by deitch — APPROVED** [review]

**Comment by aol-nnov** [comment]
Yay, cool!

**Pull request merged**
