### PR TITLE
Make fat32 ReadDir not return special volume label

### PR DESCRIPTION
**Pull request by quite**
Fixes https://github.com/diskfs/go-diskfs/issues/239

### CODE REVIEW

**Comment by deitch** [comment]
#242 fixes the tests issue, it has been merged in. Rebase on master and try again.

**Review by deitch — APPROVED** [review]
Can we simplify this?

```go
var ret []os.FileInfo
...
ret = append(ret, FileInfo{
...
})

// and then at the end
return ret, nil
```

**Review by deitch — CHANGES_REQUESTED** [review]
I meant to request changes.

**Comment by quite** [comment]
> Can we simplify this?

Of course. I took the middle way both keeping prealloc and looping only once. But it's surely premature optimization. Will fix.

**Comment by quite** [comment]
Done.

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
Thanks!

**Pull request merged**
